# This is a basic workflow to help you get started with Actions

name: Build & Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Deploys to AWS
      - name: Deploy Site
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{secrets.SSH_USERNAME}} # User of the server you want to ssh into
          
          script: |
            source activate tensorflow_p37
            cd /var/www/analysis-tool-website
            sudo git pull
            sudo git lfs pull
            sudo rm -rf ./node_modules
            sudo rm -rf ./client/node_modules
            sudo rm -rf ./client/build
            sudo npm install --unsafe-perm=true --allow-root
            cd ./client
            npm install
            npm run-script build
            cd ..
            pm2 stop bin/www
            pm2 start bin/www
            cd /var/www
            sudo rm -r public_html/*
            sudo cp -r /var/www/analysis-tool-website/client/build/* /var/www/public_html/
            
            echo 'Deployment successful'
